import React, { useState, useEffect } from 'react';
import { api } from '../../services/api.js';
import { RedFlagAlert } from '../../types/index.js';
import {
  ShieldAlert, AlertTriangle, CheckCircle2, Clock,
  ArrowRight, Phone, Volume2, Sparkles, Activity, User
} from 'lucide-react';

export const TriageDashboard: React.FC = () => {
  const [alerts, setAlerts] = useState<RedFlagAlert[]>([]);
  const [selectedAlert, setSelectedAlert] = useState<RedFlagAlert | null>(null);
  const [actionNotes, setActionNotes] = useState<string>('Immediate bedside ECG and oxygen support initiated. Dr. Sen notified.');
  const [isProcessing, setIsProcessing] = useState<boolean>(false);

  const fetchAlerts = () => {
    api.getTriageAlerts().then(setAlerts);
  };

  useEffect(() => {
    fetchAlerts();
    const interval = setInterval(fetchAlerts, 4000);
    return () => clearInterval(interval);
  }, []);

  const handleAcknowledge = async (id: string) => {
    setIsProcessing(true);
    try {
      await api.acknowledgeAlert(id, actionNotes);
      fetchAlerts();
      setSelectedAlert(null);
    } catch (e) {
      console.error(e);
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="max-w-6xl mx-auto py-6 px-4 space-y-6">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-red-900 via-slate-900 to-rose-950 text-white rounded-3xl p-6 sm:p-8 shadow-2xl border border-red-800/80 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-2 bg-red-600/80 text-white text-xs font-bold px-3 py-1 rounded-full uppercase tracking-wider mb-2">
            <ShieldAlert className="w-4 h-4" />
            Live Emergency & Red-Flag Triage Station
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight">
            Triage & Priority Queue Monitor
          </h1>
          <p className="text-xs sm:text-sm text-red-200 mt-1">
            Real-time screening alerts generated by MediKiosk AI intake terminals.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <div className="bg-red-950/80 border border-red-700/60 rounded-2xl p-3 text-center min-w-[100px]">
            <span className="text-[10px] text-red-300 font-bold uppercase block">Pending Alerts</span>
            <span className="text-3xl font-extrabold text-white">
              {alerts.filter(a => a.status === 'PENDING').length}
            </span>
          </div>
        </div>
      </div>

      {/* Alerts Feed & Detail View Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Alerts List */}
        <div className="lg:col-span-6 space-y-4">
          <h3 className="font-bold text-sm text-slate-800 dark:text-white uppercase tracking-wider flex items-center justify-between">
            <span>Incoming Triage Stream</span>
            <span className="text-xs text-slate-400 font-mono">Live Poll Active</span>
          </h3>

          {alerts.map(alert => {
            const isPending = alert.status === 'PENDING';
            const isSelected = selectedAlert?.id === alert.id;
            return (
              <div
                key={alert.id}
                onClick={() => setSelectedAlert(alert)}
                className={`cursor-pointer rounded-2xl p-5 border-2 transition-all transform hover:-translate-y-0.5 shadow-md flex flex-col justify-between ${
                  isSelected
                    ? 'border-red-600 bg-red-50 dark:bg-red-950/40 ring-4 ring-red-500/20'
                    : isPending
                    ? 'border-red-400 dark:border-red-800 bg-red-50/40 dark:bg-red-950/20 animate-pulse-slow'
                    : 'border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 opacity-80'
                }`}
              >
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-2">
                      <span className="font-mono bg-red-600 text-white font-bold text-xs px-2.5 py-0.5 rounded-full">
                        {alert.tokenNumber}
                      </span>
                      <span className="font-extrabold text-sm text-slate-900 dark:text-white">
                        {alert.patientName} ({alert.age} {alert.gender})
                      </span>
                    </div>

                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase ${
                      isPending ? 'bg-red-600 text-white animate-pulse' : 'bg-emerald-100 text-emerald-800'
                    }`}>
                      {alert.status}
                    </span>
                  </div>

                  <div className="text-xs font-bold text-red-700 dark:text-red-300">
                    Rule: {alert.triggerRule}
                  </div>

                  <p className="text-xs text-slate-600 dark:text-slate-300 mt-1 font-medium italic bg-white/60 dark:bg-slate-900/60 p-2 rounded-lg border border-slate-200 dark:border-slate-700">
                    "{alert.triggerInput}"
                  </p>
                </div>

                <div className="mt-3 pt-2 border-t border-slate-200 dark:border-slate-700 flex items-center justify-between text-[11px] text-slate-500">
                  <span>Detected: {new Date(alert.detectedAt).toLocaleTimeString()}</span>
                  <span className="text-red-600 font-bold flex items-center gap-1">
                    Take Action <ArrowRight className="w-3.5 h-3.5" />
                  </span>
                </div>
              </div>
            );
          })}
        </div>

        {/* Right: Action & Acknowledgement Drawer */}
        <div className="lg:col-span-6 bg-white dark:bg-slate-800 rounded-3xl p-6 shadow-xl border border-slate-200 dark:border-slate-700 flex flex-col justify-between">
          {selectedAlert ? (
            <div className="space-y-4">
              <div className="flex items-center justify-between pb-3 border-b border-slate-200 dark:border-slate-700">
                <div>
                  <span className="text-xs font-bold text-red-600 uppercase tracking-wider block">
                    Actioning Emergency Alert
                  </span>
                  <h3 className="text-xl font-extrabold text-slate-900 dark:text-white">
                    {selectedAlert.patientName} (Token {selectedAlert.tokenNumber})
                  </h3>
                </div>
                <span className="bg-red-600 text-white font-mono font-bold text-xs px-3 py-1 rounded-full">
                  Priority: STAT
                </span>
              </div>

              <div className="p-4 bg-red-50 dark:bg-red-950/40 rounded-2xl border border-red-200 dark:border-red-800 space-y-2 text-xs">
                <div><span className="font-bold text-red-900 dark:text-red-200">Trigger Rule:</span> {selectedAlert.triggerRule}</div>
                <div><span className="font-bold text-red-900 dark:text-red-200">Patient Response:</span> {selectedAlert.triggerInput}</div>
                <div><span className="font-bold text-red-900 dark:text-red-200">Severity:</span> {selectedAlert.severity}</div>
              </div>

              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300 mb-2">
                  Staff Clinical Action / Transfer Notes
                </label>
                <textarea
                  rows={4}
                  value={actionNotes}
                  onChange={e => setActionNotes(e.target.value)}
                  className="w-full text-xs p-3 rounded-xl border border-slate-300 dark:border-slate-600 bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-white outline-none"
                />
              </div>

              <div className="space-y-2 pt-2">
                <button
                  onClick={() => handleAcknowledge(selectedAlert.id)}
                  disabled={isProcessing}
                  className="w-full py-3.5 bg-red-600 hover:bg-red-700 text-white font-extrabold rounded-xl text-sm shadow-lg transition flex items-center justify-center gap-2"
                >
                  <CheckCircle2 className="w-5 h-5" />
                  <span>Acknowledge & Transfer to Resuscitation Bay</span>
                </button>
              </div>
            </div>
          ) : (
            <div className="py-20 text-center text-slate-400">
              <ShieldAlert className="w-16 h-16 mx-auto mb-3 opacity-40 text-red-500" />
              <p className="font-semibold text-sm">Select an alert from the left feed to review and take triage action.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
